const COUNTRIES_DATA = {
  AF: { name: "Афганистан", capital: "Кабул", population: 41128771, currency: "Афгански (AFN)", tz: "UTC+4:30" },
  AL: { name: "Албания", capital: "Тирана", population: 2837743, currency: "Лек (ALL)", tz: "UTC+1" },
  DZ: { name: "Алжир", capital: "Алжир", population: 44616624, currency: "Динар (DZD)", tz: "UTC+1" },
  AD: { name: "Андорра", capital: "Андорра-ла-Велья", population: 77265, currency: "Евро (EUR)", tz: "UTC+1" },
  AO: { name: "Ангола", capital: "Луанда", population: 35588987, currency: "Кванза (AOA)", tz: "UTC+1" },
  AG: { name: "Антигуа и Барбуда", capital: "Сент-Джонс", population: 97928, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  AR: { name: "Аргентина", capital: "Буэнос-Айрес", population: 45808747, currency: "Песо (ARS)", tz: "UTC-3" },
  AM: { name: "Армения", capital: "Ереван", population: 2777970, currency: "Драм (AMD)", tz: "UTC+4" },
  AU: { name: "Австралия", capital: "Канберра", population: 26439111, currency: "Австралийский доллар (AUD)", tz: "UTC+10" },
  AT: { name: "Австрия", capital: "Вена", population: 9104772, currency: "Евро (EUR)", tz: "UTC+1" },
  AZ: { name: "Азербайджан", capital: "Баку", population: 10110116, currency: "Манат (AZN)", tz: "UTC+4" },
  BS: { name: "Багамы", capital: "Нассау", population: 407906, currency: "Багамский доллар (BSD)", tz: "UTC-5" },
  BH: { name: "Бахрейн", capital: "Манама", population: 1472233, currency: "Динар (BHD)", tz: "UTC+3" },
  BD: { name: "Бангладеш", capital: "Дакка", population: 172954319, currency: "Така (BDT)", tz: "UTC+6" },
  BB: { name: "Барбадос", capital: "Бриджтаун", population: 281200, currency: "Барбадосский доллар (BBD)", tz: "UTC-4" },
  BY: { name: "Беларусь", capital: "Минск", population: 9398861, currency: "Белорусский рубль (BYN)", tz: "UTC+3" },
  BE: { name: "Бельгия", capital: "Брюссель", population: 11686140, currency: "Евро (EUR)", tz: "UTC+1" },
  BZ: { name: "Белиз", capital: "Бельмопан", population: 405272, currency: "Белизский доллар (BZD)", tz: "UTC-6" },
  BJ: { name: "Бенин", capital: "Порто-Ново", population: 13352864, currency: "Франк КФА (XOF)", tz: "UTC+1" },
  BT: { name: "Бутан", capital: "Тхимпху", population: 782318, currency: "Нгултрум (BTN)", tz: "UTC+6" },
  BO: { name: "Боливия", capital: "Сукре", population: 12079472, currency: "Боливиано (BOB)", tz: "UTC-4" },
  BA: { name: "Босния и Герцеговина", capital: "Сараево", population: 3233526, currency: "Марка (BAM)", tz: "UTC+1" },
  BW: { name: "Ботсвана", capital: "Габороне", population: 2397241, currency: "Пула (BWP)", tz: "UTC+2" },
  BR: { name: "Бразилия", capital: "Бразилиа", population: 216422446, currency: "Реал (BRL)", tz: "UTC-3" },
  BN: { name: "Бруней", capital: "Бандар-Сери-Бегаван", population: 449003, currency: "Брунейский доллар (BND)", tz: "UTC+8" },
  BG: { name: "Болгария", capital: "София", population: 6745677, currency: "Лев (BGN)", tz: "UTC+2" },
  BF: { name: "Буркина-Фасо", capital: "Уагадугу", population: 22673762, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  BI: { name: "Бурунди", capital: "Гитега", population: 12889576, currency: "Франк (BIF)", tz: "UTC+2" },
  KH: { name: "Камбоджа", capital: "Пномпень", population: 16944826, currency: "Риель (KHR)", tz: "UTC+7" },
  CM: { name: "Камерун", capital: "Яунде", population: 27914536, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  CA: { name: "Канада", capital: "Оттава", population: 39742430, currency: "Канадский доллар (CAD)", tz: "UTC-5" },
  CV: { name: "Кабо-Верде", capital: "Прая", population: 587925, currency: "Эскудо (CVE)", tz: "UTC-1" },
  CF: { name: "ЦАР", capital: "Банги", population: 5579144, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  TD: { name: "Чад", capital: "Нджамена", population: 18278568, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  CL: { name: "Чили", capital: "Сантьяго", population: 19491013, currency: "Песо (CLP)", tz: "UTC-4" },
  CN: { name: "Китай", capital: "Пекин", population: 1425671352, currency: "Юань (CNY)", tz: "UTC+8" },
  CO: { name: "Колумбия", capital: "Богота", population: 51874024, currency: "Песо (COP)", tz: "UTC-5" },
  KM: { name: "Коморы", capital: "Морони", population: 836774, currency: "Франк (KMF)", tz: "UTC+3" },
  CG: { name: "Конго", capital: "Браззавиль", population: 5970424, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  CD: { name: "ДР Конго", capital: "Киншаса", population: 102262808, currency: "Франк (CDF)", tz: "UTC+1" },
  CR: { name: "Коста-Рика", capital: "Сан-Хосе", population: 5212173, currency: "Колон (CRC)", tz: "UTC-6" },
  CI: { name: "Кот-д'Ивуар", capital: "Ямусукро", population: 28160542, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  HR: { name: "Хорватия", capital: "Загреб", population: 3855600, currency: "Евро (EUR)", tz: "UTC+1" },
  CU: { name: "Куба", capital: "Гавана", population: 11194449, currency: "Песо (CUP)", tz: "UTC-5" },
  CY: { name: "Кипр", capital: "Никосия", population: 1260138, currency: "Евро (EUR)", tz: "UTC+2" },
  CZ: { name: "Чехия", capital: "Прага", population: 10827529, currency: "Крона (CZK)", tz: "UTC+1" },
  DK: { name: "Дания", capital: "Копенгаген", population: 5932654, currency: "Крона (DKK)", tz: "UTC+1" },
  DJ: { name: "Джибути", capital: "Джибути", population: 1120849, currency: "Франк (DJF)", tz: "UTC+3" },
  DM: { name: "Доминика", capital: "Розо", population: 73040, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  DO: { name: "Доминикана", capital: "Санто-Доминго", population: 11117873, currency: "Песо (DOP)", tz: "UTC-4" },
  EC: { name: "Эквадор", capital: "Кито", population: 18001000, currency: "Доллар (USD)", tz: "UTC-5" },
  EG: { name: "Египет", capital: "Каир", population: 112716598, currency: "Фунт (EGP)", tz: "UTC+2" },
  SV: { name: "Сальвадор", capital: "Сан-Сальвадор", population: 6314167, currency: "Доллар (USD)", tz: "UTC-6" },
  GQ: { name: "Экваториальная Гвинея", capital: "Малабо", population: 1674908, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  ER: { name: "Эритрея", capital: "Асмэра", population: 3620312, currency: "Накфа (ERN)", tz: "UTC+3" },
  EE: { name: "Эстония", capital: "Таллин", population: 1322765, currency: "Евро (EUR)", tz: "UTC+2" },
  SZ: { name: "Эсватини", capital: "Мбабане", population: 1210822, currency: "Лилангени (SZL)", tz: "UTC+2" },
  ET: { name: "Эфиопия", capital: "Аддис-Абеба", population: 126527060, currency: "Быр (ETB)", tz: "UTC+3" },
  FJ: { name: "Фиджи", capital: "Сува", population: 936375, currency: "Фиджийский доллар (FJD)", tz: "UTC+12" },
  FI: { name: "Финляндия", capital: "Хельсинки", population: 5563970, currency: "Евро (EUR)", tz: "UTC+2" },
  FR: { name: "Франция", capital: "Париж", population: 64756584, currency: "Евро (EUR)", tz: "UTC+1" },
  GA: { name: "Габон", capital: "Либревиль", population: 2388992, currency: "Франк КФА (XAF)", tz: "UTC+1" },
  GM: { name: "Гамбия", capital: "Банжул", population: 2705992, currency: "Даласи (GMD)", tz: "UTC+0" },
  GE: { name: "Грузия", capital: "Тбилиси", population: 3728282, currency: "Лари (GEL)", tz: "UTC+4" },
  DE: { name: "Германия", capital: "Берлин", population: 83294633, currency: "Евро (EUR)", tz: "UTC+1" },
  GH: { name: "Гана", capital: "Аккра", population: 33475870, currency: "Седи (GHS)", tz: "UTC+0" },
  GR: { name: "Греция", capital: "Афины", population: 10341277, currency: "Евро (EUR)", tz: "UTC+2" },
  GD: { name: "Гренада", capital: "Сент-Джорджес", population: 124463, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  GT: { name: "Гватемала", capital: "Гватемала", population: 18092026, currency: "Кетсаль (GTQ)", tz: "UTC-6" },
  GN: { name: "Гвинея", capital: "Конакри", population: 14190612, currency: "Франк (GNF)", tz: "UTC+0" },
  GW: { name: "Гвинея-Бисау", capital: "Бисау", population: 2105566, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  GY: { name: "Гайана", capital: "Джорджтаун", population: 808726, currency: "Гайанский доллар (GYD)", tz: "UTC-4" },
  HT: { name: "Гаити", capital: "Порт-о-Пренс", population: 11724763, currency: "Гурд (HTG)", tz: "UTC-5" },
  HN: { name: "Гондурас", capital: "Тегусигальпа", population: 10432860, currency: "Лемпира (HNL)", tz: "UTC-6" },
  HU: { name: "Венгрия", capital: "Будапешт", population: 9749763, currency: "Форинт (HUF)", tz: "UTC+1" },
  IS: { name: "Исландия", capital: "Рейкьявик", population: 376248, currency: "Крона (ISK)", tz: "UTC+0" },
  IN: { name: "Индия", capital: "Нью-Дели", population: 1428627663, currency: "Рупия (INR)", tz: "UTC+5:30" },
  ID: { name: "Индонезия", capital: "Джакарта", population: 277534122, currency: "Рупия (IDR)", tz: "UTC+7" },
  IR: { name: "Иран", capital: "Тегеран", population: 87923432, currency: "Риал (IRR)", tz: "UTC+3:30" },
  IQ: { name: "Ирак", capital: "Багдад", population: 43533592, currency: "Динар (IQD)", tz: "UTC+3" },
  IE: { name: "Ирландия", capital: "Дублин", population: 5056935, currency: "Евро (EUR)", tz: "UTC+0" },
  IL: { name: "Израиль", capital: "Иерусалим", population: 9174520, currency: "Шекель (ILS)", tz: "UTC+2" },
  IT: { name: "Италия", capital: "Рим", population: 58870762, currency: "Евро (EUR)", tz: "UTC+1" },
  JM: { name: "Ямайка", capital: "Кингстон", population: 2825544, currency: "Ямайский доллар (JMD)", tz: "UTC-5" },
  JP: { name: "Япония", capital: "Токио", population: 123294513, currency: "Иена (JPY)", tz: "UTC+9" },
  JO: { name: "Иордания", capital: "Амман", population: 11337052, currency: "Динар (JOD)", tz: "UTC+2" },
  KZ: { name: "Казахстан", capital: "Астана", population: 19621800, currency: "Тенге (KZT)", tz: "UTC+5" },
  KE: { name: "Кения", capital: "Найроби", population: 55100586, currency: "Шиллинг (KES)", tz: "UTC+3" },
  KI: { name: "Кирибати", capital: "Тарава", population: 131232, currency: "Австралийский доллар (AUD)", tz: "UTC+12" },
  KW: { name: "Кувейт", capital: "Эль-Кувейт", population: 4310108, currency: "Динар (KWD)", tz: "UTC+3" },
  KG: { name: "Кыргызстан", capital: "Бишкек", population: 6974900, currency: "Сом (KGS)", tz: "UTC+6" },
  LA: { name: "Лаос", capital: "Вьентьян", population: 7529475, currency: "Кип (LAK)", tz: "UTC+7" },
  LV: { name: "Латвия", capital: "Рига", population: 1830211, currency: "Евро (EUR)", tz: "UTC+2" },
  LB: { name: "Ливан", capital: "Бейрут", population: 5353930, currency: "Фунт (LBP)", tz: "UTC+2" },
  LS: { name: "Лесото", capital: "Масеру", population: 2330318, currency: "Лоти (LSL)", tz: "UTC+2" },
  LR: { name: "Либерия", capital: "Монровия", population: 5418377, currency: "Доллар (LRD)", tz: "UTC+0" },
  LY: { name: "Ливия", capital: "Триполи", population: 6888388, currency: "Динар (LYD)", tz: "UTC+2" },
  LI: { name: "Лихтенштейн", capital: "Вадуц", population: 39326, currency: "Франк (CHF)", tz: "UTC+1" },
  LT: { name: "Литва", capital: "Вильнюс", population: 2831639, currency: "Евро (EUR)", tz: "UTC+2" },
  LU: { name: "Люксембург", capital: "Люксембург", population: 660809, currency: "Евро (EUR)", tz: "UTC+1" },
  MG: { name: "Мадагаскар", capital: "Антананариву", population: 29611714, currency: "Ариари (MGA)", tz: "UTC+3" },
  MW: { name: "Малави", capital: "Лилонгве", population: 20405317, currency: "Квача (MWK)", tz: "UTC+2" },
  MY: { name: "Малайзия", capital: "Куала-Лумпур", population: 34308525, currency: "Ринггит (MYR)", tz: "UTC+8" },
  MV: { name: "Мальдивы", capital: "Мале", population: 521021, currency: "Руфия (MVR)", tz: "UTC+5" },
  ML: { name: "Мали", capital: "Бамако", population: 22395489, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  MT: { name: "Мальта", capital: "Валлетта", population: 535064, currency: "Евро (EUR)", tz: "UTC+1" },
  MH: { name: "Маршалловы Острова", capital: "Маджуро", population: 42050, currency: "Доллар (USD)", tz: "UTC+12" },
  MR: { name: "Мавритания", capital: "Нуакшот", population: 4862989, currency: "Угия (MRU)", tz: "UTC+0" },
  MU: { name: "Маврикий", capital: "Порт-Луи", population: 1265740, currency: "Рупия (MUR)", tz: "UTC+4" },
  MX: { name: "Мексика", capital: "Мехико", population: 128901000, currency: "Песо (MXN)", tz: "UTC-6" },
  FM: { name: "Микронезия", capital: "Паликир", population: 113131, currency: "Доллар (USD)", tz: "UTC+10" },
  MD: { name: "Молдова", capital: "Кишинёв", population: 2600000, currency: "Лей (MDL)", tz: "UTC+2" },
  MC: { name: "Монако", capital: "Монако", population: 36297, currency: "Евро (EUR)", tz: "UTC+1" },
  MN: { name: "Монголия", capital: "Улан-Батор", population: 3398366, currency: "Тугрик (MNT)", tz: "UTC+8" },
  ME: { name: "Черногория", capital: "Подгорица", population: 616695, currency: "Евро (EUR)", tz: "UTC+1" },
  MA: { name: "Марокко", capital: "Рабат", population: 37840044, currency: "Дирахм (MAD)", tz: "UTC+1" },
  MZ: { name: "Мозамбик", capital: "Мапуту", population: 32969517, currency: "Метикал (MZN)", tz: "UTC+2" },
  MM: { name: "Мьянма", capital: "Нейпьидо", population: 54179306, currency: "Кьят (MMK)", tz: "UTC+6:30" },
  NA: { name: "Намибия", capital: "Виндхук", population: 2604172, currency: "Доллар (NAD)", tz: "UTC+2" },
  NR: { name: "Науру", capital: "Ярен", population: 12780, currency: "Австралийский доллар (AUD)", tz: "UTC+12" },
  NP: { name: "Непал", capital: "Катманду", population: 30896590, currency: "Рупия (NPR)", tz: "UTC+5:45" },
  NL: { name: "Нидерланды", capital: "Амстердам", population: 17618299, currency: "Евро (EUR)", tz: "UTC+1" },
  NZ: { name: "Новая Зеландия", capital: "Веллингтон", population: 5185288, currency: "Новозеландский доллар (NZD)", tz: "UTC+12" },
  NI: { name: "Никарагуа", capital: "Манагуа", population: 6948392, currency: "Кордоба (NIO)", tz: "UTC-6" },
  NE: { name: "Нигер", capital: "Ниамей", population: 26207977, currency: "Франк КФА (XOF)", tz: "UTC+1" },
  NG: { name: "Нигерия", capital: "Абуджа", population: 223804632, currency: "Найра (NGN)", tz: "UTC+1" },
  KP: { name: "Северная Корея", capital: "Пхеньян", population: 26072217, currency: "Вон (KPW)", tz: "UTC+9" },
  MK: { name: "Северная Македония", capital: "Скопье", population: 1832696, currency: "Денар (MKD)", tz: "UTC+1" },
  NO: { name: "Норвегия", capital: "Осло", population: 5474360, currency: "Крона (NOK)", tz: "UTC+1" },
  OM: { name: "Оман", capital: "Маскат", population: 4644384, currency: "Риал (OMR)", tz: "UTC+4" },
  PK: { name: "Пакистан", capital: "Исламабад", population: 240485658, currency: "Рупия (PKR)", tz: "UTC+5" },
  PW: { name: "Палау", capital: "Нгерулмуд", population: 18058, currency: "Доллар (USD)", tz: "UTC+9" },
  PA: { name: "Панама", capital: "Панама", population: 4408581, currency: "Бальбоа / Доллар (PAB/USD)", tz: "UTC-5" },
  PG: { name: "Папуа — Новая Гвинея", capital: "Порт-Морсби", population: 10329931, currency: "Кина (PGK)", tz: "UTC+10" },
  PY: { name: "Парагвай", capital: "Асунсьон", population: 6861524, currency: "Гуарани (PYG)", tz: "UTC-4" },
  PE: { name: "Перу", capital: "Лима", population: 34049588, currency: "Соль (PEN)", tz: "UTC-5" },
  PH: { name: "Филиппины", capital: "Манила", population: 117337368, currency: "Песо (PHP)", tz: "UTC+8" },
  PL: { name: "Польша", capital: "Варшава", population: 36753736, currency: "Злотый (PLN)", tz: "UTC+1" },
  PT: { name: "Португалия", capital: "Лиссабон", population: 10247605, currency: "Евро (EUR)", tz: "UTC+0" },
  QA: { name: "Катар", capital: "Доха", population: 2716391, currency: "Риал (QAR)", tz: "UTC+3" },
  KR: { name: "Южная Корея", capital: "Сеул", population: 51784059, currency: "Вон (KRW)", tz: "UTC+9" },
  RO: { name: "Румыния", capital: "Бухарест", population: 19038098, currency: "Лей (RON)", tz: "UTC+2" },
  RU: { name: "Россия", capital: "Москва", population: 144236933, currency: "Рубль (RUB)", tz: "UTC+3" },
  RW: { name: "Руанда", capital: "Кигали", population: 14094683, currency: "Франк (RWF)", tz: "UTC+2" },
  KN: { name: "Сент-Китс и Невис", capital: "Бастер", population: 47755, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  LC: { name: "Сент-Люсия", capital: "Кастриз", population: 180251, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  VC: { name: "Сент-Винсент и Гренадины", capital: "Кингстаун", population: 103698, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  WS: { name: "Самоа", capital: "Апиа", population: 225681, currency: "Тала (WST)", tz: "UTC+13" },
  SM: { name: "Сан-Марино", capital: "Сан-Марино", population: 33642, currency: "Евро (EUR)", tz: "UTC+1" },
  ST: { name: "Сан-Томе и Принсипи", capital: "Сан-Томе", population: 231856, currency: "Добра (STN)", tz: "UTC+0" },
  SA: { name: "Саудовская Аравия", capital: "Эр-Рияд", population: 36947025, currency: "Риял (SAR)", tz: "UTC+3" },
  SN: { name: "Сенегал", capital: "Дакар", population: 17763163, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  RS: { name: "Сербия", capital: "Белград", population: 6664449, currency: "Динар (RSD)", tz: "UTC+1" },
  SC: { name: "Сейшелы", capital: "Виктория", population: 119773, currency: "Сейшельская рупия (SCR)", tz: "UTC+4" },
  SL: { name: "Сьерра-Леоне", capital: "Фритаун", population: 8791092, currency: "Леоне (SLL)", tz: "UTC+0" },
  SG: { name: "Сингапур", capital: "Сингапур", population: 5917648, currency: "Сингапурский доллар (SGD)", tz: "UTC+8" },
  SK: { name: "Словакия", capital: "Братислава", population: 5424050, currency: "Евро (EUR)", tz: "UTC+1" },
  SI: { name: "Словения", capital: "Любляна", population: 2119675, currency: "Евро (EUR)", tz: "UTC+1" },
  SB: { name: "Соломоновы Острова", capital: "Хониара", population: 724273, currency: "Соломонов доллар (SBD)", tz: "UTC+11" },
  SO: { name: "Сомали", capital: "Могадишо", population: 18143378, currency: "Шиллинг (SOS)", tz: "UTC+3" },
  ZA: { name: "ЮАР", capital: "Претория", population: 60414495, currency: "Рэнд (ZAR)", tz: "UTC+2" },
  SS: { name: "Южный Судан", capital: "Джуба", population: 11088796, currency: "Южносуданский фунт (SSP)", tz: "UTC+2" },
  ES: { name: "Испания", capital: "Мадрид", population: 47519628, currency: "Евро (EUR)", tz: "UTC+1" },
  LK: { name: "Шри-Ланка", capital: "Шри-Джаяварденепура-Котте", population: 21893579, currency: "Рупия (LKR)", tz: "UTC+5:30" },
  SD: { name: "Судан", capital: "Хартум", population: 48109006, currency: "Суданский фунт (SDG)", tz: "UTC+2" },
  SR: { name: "Суринам", capital: "Парамарибо", population: 623236, currency: "Суринамский доллар (SRD)", tz: "UTC-3" },
  SE: { name: "Швеция", capital: "Стокгольм", population: 10612086, currency: "Крона (SEK)", tz: "UTC+1" },
  CH: { name: "Швейцария", capital: "Берн", population: 8796669, currency: "Франк (CHF)", tz: "UTC+1" },
  SY: { name: "Сирия", capital: "Дамаск", population: 22125249, currency: "Сирийский фунт (SYP)", tz: "UTC+2" },
  TW: { name: "Тайвань", capital: "Тайбэй", population: 23923276, currency: "Новый тайваньский доллар (TWD)", tz: "UTC+8" },
  TJ: { name: "Таджикистан", capital: "Душанбе", population: 10143543, currency: "Сомони (TJS)", tz: "UTC+5" },
  TZ: { name: "Танзания", capital: "Додома", population: 65497748, currency: "Танзанийский шиллинг (TZS)", tz: "UTC+3" },
  TH: { name: "Таиланд", capital: "Бангкок", population: 71801279, currency: "Бат (THB)", tz: "UTC+7" },
  TL: { name: "Восточный Тимор", capital: "Дили", population: 1341296, currency: "Доллар (USD)", tz: "UTC+9" },
  TG: { name: "Того", capital: "Ломе", population: 9053799, currency: "Франк КФА (XOF)", tz: "UTC+0" },
  TO: { name: "Тонга", capital: "Нукуалофа", population: 106858, currency: "Паанга (TOP)", tz: "UTC+13" },
  TT: { name: "Тринидад и Тобаго", capital: "Порт-оф-Спейн", population: 1534937, currency: "Доллар (TTD)", tz: "UTC-4" },
  TN: { name: "Тунис", capital: "Тунис", population: 12458223, currency: "Динар (TND)", tz: "UTC+1" },
  TR: { name: "Турция", capital: "Анкара", population: 85816199, currency: "Лира (TRY)", tz: "UTC+3" },
  TM: { name: "Туркменистан", capital: "Ашхабад", population: 6516100, currency: "Манат (TMT)", tz: "UTC+5" },
  TV: { name: "Тувалу", capital: "Фунафути", population: 11396, currency: "Австралийский доллар (AUD)", tz: "UTC+12" },
  UG: { name: "Уганда", capital: "Кампала", population: 48582334, currency: "Угандийский шиллинг (UGX)", tz: "UTC+3" },
  UA: { name: "Украина", capital: "Киев", population: 36744634, currency: "Гривна (UAH)", tz: "UTC+2" },
  AE: { name: "ОАЭ", capital: "Абу-Даби", population: 9441129, currency: "Дирхам (AED)", tz: "UTC+4" },
  GB: { name: "Великобритания", capital: "Лондон", population: 67736802, currency: "Фунт стерлингов (GBP)", tz: "UTC+0" },
  US: { name: "США", capital: "Вашингтон", population: 339996563, currency: "Доллар (USD)", tz: "UTC-5" },
  UY: { name: "Уругвай", capital: "Монтевидео", population: 3423108, currency: "Песо (UYU)", tz: "UTC-3" },
  UZ: { name: "Узбекистан", capital: "Ташкент", population: 35163944, currency: "Сум (UZS)", tz: "UTC+5" },
  VU: { name: "Вануату", capital: "Порт-Вила", population: 326740, currency: "Вату (VUV)", tz: "UTC+11" },
  VE: { name: "Венесуэла", capital: "Каракас", population: 28838499, currency: "Боливар (VES)", tz: "UTC-4" },
  VN: { name: "Вьетнам", capital: "Ханой", population: 98858950, currency: "Донг (VND)", tz: "UTC+7" },
  YE: { name: "Йемен", capital: "Сана", population: 34449825, currency: "Риал (YER)", tz: "UTC+3" },
  ZM: { name: "Замбия", capital: "Лусака", population: 20569737, currency: "Квача (ZMW)", tz: "UTC+2" },
  ZW: { name: "Зимбабве", capital: "Хараре", population: 16665409, currency: "Доллар (ZWL)", tz: "UTC+2" },
  XK: { name: "Косово", capital: "Приштина", population: 1873024, currency: "Евро (EUR)", tz: "UTC+1" },
  SS: { name: "Южный Судан", capital: "Джуба", population: 11088796, currency: "Южносуданский фунт (SSP)", tz: "UTC+2" },
  PS: { name: "Палестина", capital: "Рамалла", population: 5483450, currency: "Иорданский динар (JOD)", tz: "UTC+2" },
  PR: { name: "Пуэрто-Рико", capital: "Сан-Хуан", population: 3205691, currency: "Доллар (USD)", tz: "UTC-4" },
  HK: { name: "Гонконг", capital: "Гонконг", population: 7491609, currency: "Гонконгский доллар (HKD)", tz: "UTC+8" },
  MO: { name: "Макао", capital: "Макао", population: 695168, currency: "Патака (MOP)", tz: "UTC+8" },
  GL: { name: "Гренландия", capital: "Нуук", population: 56865, currency: "Датская крона (DKK)", tz: "UTC-3" },
  NC: { name: "Новая Каледония", capital: "Нумеа", population: 289950, currency: "Франк (XPF)", tz: "UTC+11" },
  PF: { name: "Французская Полинезия", capital: "Папеэте", population: 280803, currency: "Франк (XPF)", tz: "UTC-10" },
  GF: { name: "Французская Гвиана", capital: "Кайенна", population: 312265, currency: "Евро (EUR)", tz: "UTC-3" },
  RE: { name: "Реюньон", capital: "Сен-Дени", population: 883234, currency: "Евро (EUR)", tz: "UTC+4" },
  GU: { name: "Гуам", capital: "Хагатна", population: 172952, currency: "Доллар (USD)", tz: "UTC+10" },
  VI: { name: "Американские Виргинские острова", capital: "Шарлотта-Амалия", population: 87146, currency: "Доллар (USD)", tz: "UTC-4" },
  AI: { name: "Ангилья", capital: "Вали", population: 15908, currency: "Восточнокарибский доллар (XCD)", tz: "UTC-4" },
  BM: { name: "Бермуды", capital: "Гамильтон", population: 64064, currency: "Бермудский доллар (BMD)", tz: "UTC-4" },
  KY: { name: "Каймановы острова", capital: "Джорджтаун", population: 68138, currency: "Кайманов доллар (KYD)", tz: "UTC-5" },
  GI: { name: "Гибралтар", capital: "Гибралтар", population: 32694, currency: "Фунт (GIP)", tz: "UTC+1" },
  FO: { name: "Фарерские острова", capital: "Торсхавн", population: 54677, currency: "Датская крона (DKK)", tz: "UTC+0" },
  JE: { name: "Джерси", capital: "Сент-Хелиер", population: 100080, currency: "Фунт (JEP)", tz: "UTC+0" },
  GG: { name: "Гернси", capital: "Сент-Питер-Порт", population: 63544, currency: "Фунт (GGP)", tz: "UTC+0" },
  IM: { name: "Остров Мэн", capital: "Дуглас", population: 84711, currency: "Фунт (IMP)", tz: "UTC+0" },
  BM: { name: "Бермуды", capital: "Гамильтон", population: 64064, currency: "Бермудский доллар (BMD)", tz: "UTC-4" },
  TC: { name: "Теркс и Кайкос", capital: "Коберн-Таун", population: 46062, currency: "Доллар (USD)", tz: "UTC-5" },
  VU: { name: "Вануату", capital: "Порт-Вила", population: 326740, currency: "Вату (VUV)", tz: "UTC+11" },
  FK: { name: "Фолклендские острова", capital: "Стэнли", population: 3662, currency: "Фунт (FKP)", tz: "UTC-3" },
  SH: { name: "Остров Святой Елены", capital: "Джеймстаун", population: 6077, currency: "Фунт (SHP)", tz: "UTC+0" },
  PN: { name: "Остров Питкэрн", capital: "Адамстаун", population: 56, currency: "Новозеландский доллар (NZD)", tz: "UTC-8" },
  IO: { name: "Британская территория в Индийском океане", capital: "Диего-Гарсия", population: 3000, currency: "Доллар (USD)", tz: "UTC+6" },
  AQ: { name: "Антарктида", capital: "Н/A", population: 4490, currency: "N/A", tz: "UTC+0" },
};

export function getLocalCountryData(alpha2) {
  return COUNTRIES_DATA[alpha2] || null;
}

export function formatPop(pop) {
  if (pop >= 1e9) return (pop / 1e9).toFixed(2) + ' млрд';
  if (pop >= 1e6) return (pop / 1e6).toFixed(2) + ' млн';
  if (pop >= 1e3) return (pop / 1e3).toFixed(1) + ' тыс.';
  return pop.toString();
}
